# Generated by Django 4.2.23 on 2025-08-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_bills_and_transform_projects'),
        ('projects', '0003_project_document'),
    ]

    operations = [
    ]
