# Generated by Django 4.2.23 on 2025-08-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_projects_pr_status_af6027_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('first_reading', 'First Reading'), ('committee_stage', 'Committee Stage'), ('second_reading', 'Second Reading'), ('third_reading', 'Third Reading'), ('presidential_assent', 'Presidential Assent'), ('enacted', 'Enacted'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
    ]
