# Generated by Django 4.2.23 on 2025-08-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, help_text='Official bill number (e.g., HB-2024-001)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='committee',
            field=models.CharField(blank=True, help_text='Parliamentary committee handling the bill', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='committee_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='first_reading_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bills/images/'),
        ),
        migrations.AddField(
            model_name='bill',
            name='introduced_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='public_participation_open',
            field=models.BooleanField(default=True),
        ),
    ]
