# Generated by Django 4.2.23 on 2025-08-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_add_bill_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='extraction_method',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='processing_metadata',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='processing_time',
        ),
    ]
