# Generated by Django 4.2.23 on 2025-08-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_bill_bill_number_bill_committee_and_more'),
        ('projects', '0012_add_progress_tracking_fields'),
    ]

    operations = [
    ]
