# Generated by Django 4.2.23 on 2025-08-31 22:29

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_billchunk_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
    ]
