# Generated by Django 4.2.23 on 2025-09-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_fix_bill_fields_safely'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, help_text='Official bill number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='committee',
            field=models.CharField(blank=True, help_text='Committee handling the bill', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='committee_deadline',
            field=models.DateField(blank=True, help_text='Committee review deadline', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='first_reading_date',
            field=models.DateField(blank=True, help_text='Date of first reading', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='image',
            field=models.ImageField(blank=True, help_text='Bill image or cover', null=True, upload_to='bills/'),
        ),
        migrations.AddField(
            model_name='bill',
            name='introduced_date',
            field=models.DateField(blank=True, help_text='Date bill was introduced', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='public_participation_open',
            field=models.BooleanField(default=True, help_text='Whether public participation is open for this bill'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['status', 'public_participation_open'], name='projects_bi_status_07c63a_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['bill_number'], name='projects_bi_bill_nu_9ea1b5_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['introduced_date'], name='projects_bi_introdu_e665ec_idx'),
        ),
    ]
