# Generated by Django 4.2.23 on 2025-08-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_can_delete_feedback_can_edit_and_more'),
        ('feedback', '0002_transform_to_national_assembly'),
    ]

    operations = [
    ]
