# Generated by Django 4.2.23 on 2025-08-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_feedback_feedback_fe_county__55692a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feedback',
            name='feedback_fe_trackin_9d4d63_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='feedback_fe_user_co_bf5a78_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='feedback_fe_created_9e3e55_idx',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='last_response_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='response_count',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='tracking_id',
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['user_county', 'created_at'], name='feedback_fe_user_co_6218e3_idx'),
        ),
    ]
