# Generated by Django 4.2.23 on 2025-08-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_remove_feedback_feedback_fe_trackin_9d4d63_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='last_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='response_count',
            field=models.IntegerField(default=0),
        ),
    ]
