# Generated by Django 4.2.23 on 2025-08-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_feedback_last_response_at_feedback_response_count'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feedback',
            name='feedback_fe_categor_4ef27f_idx',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='feedbackedit',
            name='previous_category',
        ),
    ]
