# Generated by Django 4.2.23 on 2025-08-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
        ('users', '0002_transform_to_national_assembly'),
    ]

    operations = [
    ]
