# Generated by Django 4.2.23 on 2025-08-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20250825_1545'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_tenant__29ab49_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_home_co_03e940_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_role_1e8639_idx',
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_county', 'role'], name='users_custo_user_co_91bfed_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'admin_level'], name='users_custo_role_01ab3f_idx'),
        ),
    ]
