# Generated by Django 4.2.23 on 2025-08-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fix_existing_users'),
        ('users', '0004_remove_customuser_users_custo_tenant__29ab49_idx_and_more'),
    ]

    operations = [
    ]
